# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da8087f37c60029bcc0003ae5c79be09b4e4a5b48a159c40e164f4dd6748294615115aa6f4e3422acaefdc757fe0a8973e12a39c2e4a8e6a1b872e0acb9b5940

test:
  secret_key_base: d8a5d72db82c92f9f1ed6a0aadabef8cf1bd7ec23e95a506a08c416e1c810c8149c49f7ee2ea07feb9ba3e6250480722ef5b510d3e480f8b7e02d6bf757c9471

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
